title: PGCoE SC2 Test Site
description: Supplemental NCBI documentation for public health scientists.
theme: just-the-docs

url: https://nwpage.org/

aux_links:
  PGCoE Main Site: https://pgcoe.github.io/

heading_anchors: true

callouts:
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green
  important:
    title: Important
    color: purple
  warning:
    title: Warning
    color: red
  example:
    title: Example
    color: yellow